on:
  push:
    branches:
      - main

name: algolia-search
jobs:
  algolia-search:
    runs-on: ubuntu-latest
    env:
      JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.3'

      - name: Update RubyGems
        run: gem update --system 3.2.3

      - name: Algolia Jekyll Action
        uses: dieghernan/algolia-jekyll-action@main
        with:
          APIKEY: '${{ secrets.ALGOLIA_API_KEY }}'